# Generated by Django 5.0.1 on 2024-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(default='Computer Science', max_length=50)),
                ('gender', models.CharField(default='m', max_length=1, null=True)),
                ('rollNo', models.IntegerField(null=True)),
                ('clg_roll_no', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
