# Generated by Django 5.0.7 on 2024-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginCredentials",
            fields=[
                (
                    "userName",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("passwd", models.CharField(default="Atul", max_length=20)),
                ("email", models.EmailField(default="    @gamil.com", max_length=254)),
            ],
        ),
    ]
