# Generated by Django 5.0.7 on 2024-08-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookStore", "0004_alter_books_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="category",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookStore.categories",
            ),
        ),
    ]
