# Generated by Django 5.0.7 on 2024-08-01 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookStore", "0006_alter_books_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Average_rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_rating", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="books",
            name="average_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookStore.average_rating",
            ),
        ),
    ]
