# Generated by Django 5.0.7 on 2024-07-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="games",
            fields=[
                (
                    "gID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("gName", models.CharField(max_length=30)),
                ("gTag", models.CharField(max_length=10, null=True)),
                ("gDesc", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
